apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: siren-product-deployment
  labels:
    app: siren-product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: siren-product
  template:
    metadata:
      labels:
        app: siren-product
    spec:
      containers:
      - name: siren-product
        image: goblin8621/siren-product:0.0.1
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
